version: '3.1'

services:

  mysql:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root # Change Me
      MYSQL_DATABASE: otservbr-global # Change Me
      MYSQL_USER: otservbr-global # Change Me
      MYSQL_PASSWORD: otservbr-global # Change Me
    ports:
      - 3306:3306
    volumes:
      - canary-db:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - canary

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - canary
    depends_on:
      - mysql
  # server:
  #   build:
  #     context: .
  #     dockerfile: docker/Dockerfile.x86
  #   volumes:
  #     - canary-server:/canary
  #   depends_on:
  #     - mysql

networks:
  canary:
    name: canary

volumes:
  canary-db:
